defaults:
  - model_checkpoint
  # - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch_{epoch:03d}"
  # monitor: "val/loss"
  # mode: "min"
  save_last: true
  save_top_k: 0
  auto_insert_metric_name: false

# early_stopping:
#   monitor: "val/loss"
#   patience: 20
#   mode: "min"

model_summary:
  max_depth: -1
